# Generated by Django 5.0.4 on 2024-05-06 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_cat', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('refrigerator', 'Refrigerator'), ('washing_mach', 'Washing Machine')], db_index=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Refrigerators',
            fields=[
                ('id_ref', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('amount_compressor', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.category')),
            ],
        ),
    ]
