# Generated by Django 5.0.4 on 2024-05-09 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_compressor_refrigerator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressor',
            name='refrigerator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.refrigerator'),
        ),
        migrations.AlterField(
            model_name='researchref',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.refrigerator'),
        ),
    ]
