# Generated by Django 5.0.4 on 2024-05-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_categories_category_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refrigerators',
            new_name='Refrigerator',
        ),
    ]
