# Generated by Django 5.0.4 on 2024-05-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_refrigerators_refrigerator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='refrigerator',
            options={'ordering': ['name', 'amount_compressor', 'category'], 'verbose_name': 'Refrigerator', 'verbose_name_plural': 'Refrigerators'},
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='no_frost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('refrigerator', 'Refrigerator'), ('washing_mach', 'Washing Machine')], db_index=True, max_length=50),
        ),
    ]
