# Generated by Django 5.0.4 on 2024-05-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_category_options_alter_refrigerator_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refrigerator',
            options={'ordering': ['name', 'amount_compressor', 'no_frost', 'category'], 'verbose_name': 'Refrigerator', 'verbose_name_plural': 'Refrigerators'},
        ),
    ]
