# Generated by Django 5.0.4 on 2024-05-09 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_refrigerator_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRef',
            fields=[
                ('id_res', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('describe', models.TextField(blank=True, help_text='Additional info about research', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail'), ('in_process', 'In Process')], db_index=True, max_length=50)),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField(blank=True, null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.refrigerator')),
            ],
        ),
    ]
