# Generated by Django 5.0.4 on 2024-05-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_researchref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchref',
            options={'ordering': ['id_res', 'device', 'status', 'date_start', 'date_finish'], 'verbose_name': 'Refrigerator research', 'verbose_name_plural': 'Refrigerator research'},
        ),
    ]
