# Generated by Django 5.0.4 on 2024-05-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_category_name_alter_researchref_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Compressor model')),
                ('refrigerator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.refrigerator')),
            ],
            options={
                'verbose_name': 'Compressor',
                'verbose_name_plural': 'Compressors',
                'ordering': ['name'],
            },
        ),
    ]
